// <auto-generated />
using System;
using Api.Context.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace picpay_simplificado.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Transference.Model.TransferenceModel", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beneficiario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfBeneficiario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCedente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransferId");

                    b.ToTable("Transferences");
                });

            modelBuilder.Entity("Usuarios.Model.UsuariosModel", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoUsuairio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("saldo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Email");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
